# Generated by Django 5.2.11 on 2026-06-15 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_category_tests_alter_test_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.BigIntegerField(db_index=True)),
                ('patient_id', models.BigIntegerField(db_index=True)),
                ('invoice_item_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('test_service_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('agency_change_reason', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('INHOUSE', 'Inhouse'), ('OUTSOURCE', 'Outsource')], db_index=True, default='INHOUSE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('RESAMPLING', 'Resampling'), ('RESULT_PENDING', 'Result Pending'), ('RESULT_ENTERED', 'Result Entered'), ('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='COLLECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collection_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection_per_order_test',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='collections_work_or_8be316_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='collections_status_17d171_idx',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='agency_change_reason',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='billing_source_code',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='billing_source_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='billing_source_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='billing_source_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collected_by_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cycle_number',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='invoice_item_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_from_package',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_refunded',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_mrn',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='patient_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='test',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='test_service_code',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='test_service_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='test_service_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='visit_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='work_order_id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('RESAMPLING', 'Resampling'), ('RESULT_PENDING', 'Result Pending'), ('RESULT_ENTERED', 'Result Entered'), ('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='COLLECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='collectiontest',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_tests', to='restapi.agency'),
        ),
        migrations.AddField(
            model_name='collectiontest',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_tests', to='restapi.collection'),
        ),
        migrations.AddField(
            model_name='collectiontest',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_tests', to='restapi.sample'),
        ),
        migrations.AddField(
            model_name='collectiontest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_tests', to='restapi.test'),
        ),
        migrations.AddConstraint(
            model_name='collectiontest',
            constraint=models.UniqueConstraint(fields=('work_order_id', 'invoice_item_id'), name='unique_collection_test_per_order_item'),
        ),
    ]
